safe: true
markdown: kramdown
highlighter: rouge
permalink: /:title.html
relative_permalinks: false

default_theme: yandex2
default_width: 1024
default_ratio: 16x9
default_lang: en

presentation:
    title: Symfoniacs spb 3
    nda: false
    lang: ru

author:
    name: Ханов Руслан
    position: Разработчик
    company:
        name: Symfoniacs
        url:  http://symfoniacs.ru

progress: false
